### PR TITLE
Added Adivvyo theme

### PR DESCRIPTION
**Pull request by hightowe**

### CODE REVIEW

**Comment by robiso** [comment]
@hightowe thanks for the theme.
I believe 1 or 2 fixes will be necessary (as can be seen in the screenshot below) before this theme can be added to the repository.

1. Logo isn't loaded.
2 Footer is not full width:
Screenshot 2020-02-10 at 20 50 27

(Tested on Macbook Pro - Mojave 10.14.6 - latest Firefox version)

**Comment by hightowe** [comment]
@robiso -

The **title_logo.png** that you see is, in fact, the file title_logo.png on disk that ships with the theme. The intent is for the user to remove it (and then the site title text would then be used) or replace it with their own title_logo.png.

I can't explain the lack of full width in the footer. Not seeing that here. I'll look into it.

--
Lester

**Comment by robiso** [comment]
@hightowe, cheers for explaining the title, makes sense.

In regards to the width: changing container to container-fluid might fix this (but I'm not sure if this is the wanted behaviour) - for me, this made the whole footer 100% width as can be seen below.

Screenshot 2020-02-10 at 22 00 54

**Comment by hightowe** [comment]
I don't understand why yet, but the footer only fails to be 100% wide when you are logged in. If you logout, it should be fixed. I'm still investigating as I would like to understand the cause before implementing a "fix" ...

**Comment by hightowe** [comment]
I just published an update that should fix it -- your suggestion.

**Comment by robiso** [comment]
Approved. :)
Will be mentioned in the new WonderCMS 3.0.6 release in the next hour.
https://www.wondercms.com/whatsnew

**Pull request merged**
